Nyt data
prendradjaja/covid-dashboard pull request #12
Opened 2020-04-07 05:54 UTC by sollipse

Depends on #11

2020-04-08 02:58 UTC, prendradjaja commented
changed base branch for easier diffing

2020-04-08 03:03 UTC, prendradjaja requested changes
A few things. Might be a bit involved. We could leave to a later PR or I could do some of these things. In any case maybe we get #11 merged first though before working on this!

2020-04-08 03:03 UTC, prendradjaja commented on src/app/nyt-fetcher.service.ts
> +}
Would be nice to DRY this out (duplicated between here and CdsFetcherService)

2020-04-08 03:03 UTC, prendradjaja commented on src/app/nyt-fetcher.service.ts
> +const convertNYTArrayToCoronaDatapoint = ([
Probably we should have some datapoint concept of our own that we convert both NYT and CDS to (as opposed to converting NYT to CDS)

2020-04-08 03:03 UTC, prendradjaja commented on src/app/nyt-fetcher.service.ts
> +  parse(dateString, 'yyyy-MM-dd', new Date(1984, 0, 1));
Duplicated with CDS. Anyway let's rename to "parseIsoDate" or something

2020-04-18 19:30 UTC, prendradjaja commented
@sollipse Anything to keep from this branch or shall we close this PR now (bc of the Lambda)?

2020-04-18 21:30 UTC, sollipse commented
No need, this is redundant

2020-04-18 21:30 UTC, closed without merging